// Generated by CoffeeScript 1.6.3
define("decisionlog/core/model/entry", [], function() {
  var Entry;
  return Entry = (function() {
    function Entry() {}

    Entry.prototype.answer = function() {};

    return Entry;

  })();
});
